# Generated by Django 6.0.6 on 2026-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.IntegerField(help_text='Idade em meses')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível para adoção'), ('ADOTADO', 'Já adotado'), ('TRATAMENTO', 'Em tratamento médico')], default='DISPONIVEL', max_length=20)),
            ],
        ),
    ]
